# Generated by Django 4.0.6 on 2022-07-18 17:53

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0002_alter_agenda_dia_alter_horario_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TimeField(max_length=6), size=None),
        ),
    ]
