# Generated by Django 4.0.6 on 2022-07-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0003_alter_horario_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='disponivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='horario',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='medicar.agenda'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.TimeField(),
        ),
    ]
