# Generated by Django 4.0.6 on 2022-07-18 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0005_alter_agenda_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('medico', 'dia')},
        ),
    ]
