# Generated by Django 4.0.6 on 2022-07-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0008_especialidades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialidades',
            new_name='Especialidade',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidades',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicar.especialidade'),
            preserve_default=False,
        ),
    ]
